---
# Site settings
title: Health Haven
description: Your go-to blog for health and fitness tips
author: Ebenezer
baseurl: /myhealthaven # Change to match your repository name
url: https://ebenezer129dotcom.github.io # Your GitHub Pages URL

# Theme settings
theme: minima
minima:
  skin: auto # Optional: Uses system's dark/light mode preference
  date_format: "%b %-d, %Y" # e.g., Aug 23, 2025

# Header and navigation
header_pages:
  - index.md
  - about.md
  - health-tips.md
  - contact.md

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
